const actionTypes = {
    OBJECT_ADD_START:'OBJECT_ADD_START',
    OBJECT_ADD_SUCCESS:'OBJECT_ADD_SUCCESS',
    OBJECT_ADD_FAILURE:'OBJECT_ADD_FAILURE',
    LOAD_OPTIONS: 'LOAD_OPTIONS',
    START_FETCH_OBJECTS: 'START_FETCH_OBJECTS',
    SUCCESS_FETCH_OBJECTS: 'SUCCESS_FETCH_OBJECTS',
    FAILURE_FETCH_OBJECTS: 'FAILURE_FETCH_OBJECTS'
}

export default actionTypes