const actionTypes = {
    OBJECT_ADD_START:'OBJECT_ADD_START',
    OBJECT_ADD_SUCCESS:'OBJECT_ADD_SUCCESS',
    OBJECT_ADD_FAILURE:'OBJECT_ADD_FAILURE',
    LOAD_OPTIONS: 'LOAD_OPTIONS_SUCCESS',
    START_FETCH_OBJECTS: 'START_FETCH_OBJECTS',
    SUCCESS_FETCH_OBJECTS: 'SUCCESS_FETCH_OBJECTS',
    FAILURE_FETCH_OBJECTS: 'FAILURE_FETCH_OBJECTS',
    START_DELETE_OBJECT: 'START_DELETE_OBJECT',
    FAILURE_DELETE_OBJECT: 'FAILURE_DELETE_OBJECT',
    SUCCESS_DELETE_OBJECT: 'SUCCESS_DELETE_OBJECT',
    FETCH_ONE_OBJECT_START: 'FETCH_ONE_OBJECT_START',
    FETCH_ONE_OBJECT_SUCCESS: 'FETCH_ONE_OBJECT_SUCCESS',
    FETCH_ONE_OBJECT_FAILURE: 'FETCH_ONE_OBJECT_FAILURE',
    OBJECT_UPDATE_START:'OBJECT_UPDATE_START',
    OBJECT_UPDATE_SUCCESS:'OBJECT_UPDATE_SUCCESS',
    OBJECT_UPDATE_FAILURE:'OBJECT_UPDATE_FAILURE',
    CLEAR_UPDATE_OBJECT:'CLEAR_UPDATE_OBJECT',
    FETCH_PRODUCTS_BY_STRING: 'FETCH_PRODUCTS_BY_STRING',
    FETCH_PRODUCTS_BY_STRING_SUCCESS: 'FETCH_PRODUCTS_BY_STRING_SUCCESS',
    FETCH_PRODUCTS_BY_STRING_FAILURE: 'FETCH_PRODUCTS_BY_STRING_FAILURE',
    SHOW_SUCCESS: 'SHOW_SUCCESS',
    REMOVE_SUCCESS: 'REMOVE_SUCCESS'
}

export default actionTypes